# Generated by Django 2.0.5 on 2018-06-01 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flying',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
