# Generated by Django 2.0.5 on 2018-06-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0002_auto_20180601_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flying',
            old_name='user_id',
            new_name='user',
        ),
    ]
